default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_api_development
  username: my_api_user
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: my_api_test
  username: my_api_user
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: my_api_production
  username: my_api_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: 5432